### ISSUE TITLE
Sprint 1: TODO

### ISSUE THREAD

**Issue by bboe** [scalableinternetservices/teamtrader#4]
- [x] Please add link to pivotal tracker project in readme
- [x] Please expand a little on the project description. Perhaps a little detail about the algorithm, or describe how a user might actually use your system.

Regarding your sprint 1 commitment, it looks great. Please keep in mind what we discussed yesterday about focusing on adding complexity to your webservice and less initially upon talking with third party services. If you need to adjust your commitment please do. Also, try to assign some point estimate to stories in the "current" section so you can over the next few weeks get a feel for how many "points" worth of work you can pull in.

**Comment by bboe** [comment]
Can I please get an update on this issue?

**Comment by sharathrao13** [comment]
Hi!
I just updated the read me file to include more details on what we are offering to users. I also updated the link to pivotal tracker.  We are currently working on the stories in the Current section. We have created different feature branches. We are looking at completing most of it.

**Comment by bboe** [comment]
Fantastic! Thanks.
